### ISSUE TITLE
no module Bio

### ISSUE THREAD

**Issue by matiajan** [guogenglin/SsuisChara#1]
When I try to run SuisChara on Debian 11, blast+ and prodigal installed, I got this message:
(base) honza@T-30:~/Downloads/SsuisChara-main$ python SsuisChara.py -i *.fasta 
Traceback (most recent call last):
  File "/home/honza/Downloads/SsuisChara-main/SsuisChara.py", line 15, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

Should I install some Bio module?

**Comment by guogenglin** [comment]
Yes, biopython module is required for SsuisChara, try to install this module by pip:
pip install biopython

**Comment by matiajan** [comment]
I installed biopython as you recommended, add /usr/local/lib/python3.9/dist-packages/Bio into PATH but still got the same message:
(base) honza@T-30:~/Downloads/SsuisChara-main$ echo $PATH
/usr/local/lib/python3.9/dist-packages/Bio:/home/honza/anaconda3/bin:/home/honza/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
(base) honza@T-30:~/Downloads/SsuisChara-main$ python SsuisChara.py -i *.fasta 
Traceback (most recent call last):
  File "/home/honza/Downloads/SsuisChara-main/SsuisChara.py", line 15, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by guogenglin** [comment]
This may because of the setting of your system or python, you can get help from the official website of biopython: https://biopython.org/
